apiVersion: v1
kind: Template
metadata:
  name: minio-backup
parameters:
  - name: VERSION
    value: latest
  - name: NAMESPACE
    value: esm
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        name: epic-documents-backup
      name: epic-documents-backup
      namespace: "${NAMESPACE}"
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        name: "epic-documents-backup"
        version: ${VERSION}
      name: "epic-documents-backup"
      namespace: "${NAMESPACE}"
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: epic-documents-backup:${VERSION}
      postCommit: {}
      resources: {}
      source:
        git:
          uri: https://github.com/bcgov/eagle-api.git
          ref: develop
        contextDir: openshift/templates/jobs/minio-backup
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: alpine:3.7
            namespace: openshift
        type: Docker
      triggers:
      - type: ConfigChange
    status:
      lastVersion: 0
